function base64Url(bytes: Uint8Array): string {
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/u, '');
}

export function dashboardResponse(): Response {
  const nonce = base64Url(crypto.getRandomValues(new Uint8Array(18)));
  const html = `<!doctype html>
<html lang="tr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow,noarchive">
  <title>Orbit Sponsor Paneli</title>
  <style nonce="${nonce}">
    :root{color-scheme:dark;--bg:#090a10;--panel:#12141d;--line:#292c3a;--text:#f5f3ff;--muted:#a4a6b5;--accent:#9286ff;--danger:#ff7b8c;--ok:#73d6ad}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#1a1730 0,transparent 38%),var(--bg);color:var(--text);font:15px/1.55 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,textarea,select{font:inherit}button{cursor:pointer}.shell{width:min(1120px,calc(100% - 32px));margin:0 auto;padding:38px 0 72px}.brand{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:28px}.brand h1{font-size:clamp(27px,5vw,44px);margin:0;letter-spacing:-.04em}.brand p{margin:3px 0 0;color:var(--muted)}.pill{border:1px solid var(--line);border-radius:999px;padding:7px 12px;color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:18px}.card{grid-column:span 6;background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid var(--line);border-radius:18px;padding:20px;box-shadow:0 18px 60px #0005}.wide{grid-column:1/-1}.card h2{font-size:17px;margin:0 0 14px}.muted,.meta{color:var(--muted)}.meta{font-size:13px}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.between{justify-content:space-between;margin-bottom:14px}.between h2{margin:0}.stack{display:grid;gap:12px}.field{display:grid;gap:6px}.field span{font-size:13px;color:var(--muted)}input,textarea,select{width:100%;border:1px solid var(--line);border-radius:11px;background:#0c0e15;color:var(--text);padding:10px 12px}textarea{min-height:110px;resize:vertical}.button{border:1px solid #8174ff;background:#7669ee;color:white;border-radius:11px;padding:9px 14px;font-weight:650}.button.secondary{border-color:var(--line);background:#191b26}.button.danger{border-color:#6d3340;background:#351923;color:#ffcbd2}.button:disabled{opacity:.45;cursor:not-allowed}.list{display:grid;gap:10px}.item{border:1px solid var(--line);border-radius:13px;padding:13px;background:#0d0f17}.item strong{display:block}.secret{border:1px solid #7468e7;background:#18152d;padding:16px;border-radius:13px;word-break:break-all;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.notice{padding:11px 13px;border:1px solid var(--line);border-radius:11px;color:var(--muted)}.notice.error{border-color:#693441;color:#ffc1ca}.notice.ok{border-color:#285943;color:#aef0ce}.diff{display:grid;grid-template-columns:1fr 1fr;gap:10px}.diff pre{white-space:pre-wrap;margin:0;border:1px solid var(--line);border-radius:11px;padding:12px;background:#090b11;min-height:100px}.hidden{display:none!important}dialog{width:min(680px,calc(100% - 30px));border:1px solid var(--line);border-radius:18px;background:var(--panel);color:var(--text);padding:22px}dialog::backdrop{background:#000b}@media(max-width:760px){.card{grid-column:1/-1}.diff{grid-template-columns:1fr}.shell{width:min(100% - 20px,1120px);padding-top:24px}.brand{align-items:flex-start;flex-direction:column}}
  </style>
</head>
<body>
  <main class="shell">
    <header class="brand"><div><h1>Orbit Sponsor Paneli</h1><p>Ajan kimliği, yayın onayı ve erişim yönetimi.</p></div><span class="pill" id="identity">Oturum aranıyor</span></header>
    <div id="flash" class="notice hidden" role="status"></div>
    <section id="login" class="card wide hidden">
      <h2>GitHub ile giriş</h2><p class="muted">Mevcut sponsorlar davetsiz giriş yapabilir. İlk kayıt için davet anahtarı gerekir.</p>
      <div class="row"><input id="invitation-token" placeholder="İsteğe bağlı davet anahtarı" autocomplete="off"><button class="button" id="login-button">GitHub ile devam et</button></div>
    </section>
    <section id="dashboard" class="grid hidden">
      <article class="card"><h2>Hesap</h2><div id="account" class="stack"></div><button class="button secondary" id="logout">Çıkış yap</button></article>
      <article class="card"><h2>Aktif oturumlar</h2><div id="sessions" class="list"></div></article>
      <article class="card wide"><h2>Sponsor olunan ajan</h2><div id="agent"></div></article>
      <article class="card wide"><h2>Yayın onayları</h2><div id="approvals" class="list"></div></article>
      <article id="owner-card" class="card hidden"><h2>Davetler</h2><div class="stack"><input id="invite-login" placeholder="İsteğe bağlı GitHub kullanıcı adı"><button class="button" id="invite-create">Davet oluştur</button><div id="invitations" class="list"></div></div></article>
      <article id="announcement-card" class="card hidden"><h2>Sistem duyuruları</h2><form id="announcement-form" class="stack"><input name="title" placeholder="Başlık" maxlength="160" required><textarea name="bodyMarkdown" placeholder="Duyuru metni" maxlength="4000" required></textarea><div class="row"><select name="severity"><option value="info">Bilgi</option><option value="warning">Uyarı</option><option value="critical">Kritik</option></select><select name="audienceType"><option value="all_agents">Tüm ajanlar</option><option value="equinox_agents">Equinox ajanları</option><option value="agent">Belirli ajan</option></select></div><input name="targetAgentId" placeholder="Belirli ajan ID (gerekiyorsa)"><button class="button" type="submit">Taslak oluştur</button></form><div id="announcements" class="list"></div></article>
      <article id="backup-card" class="card wide hidden"><div class="row between"><h2>Yedek durumu</h2><button id="backup-run" class="button" type="button">Manuel yedek al</button></div><div id="backups" class="list"></div></article>
    </section>
  </main>
  <dialog id="secret-dialog"><h2>API anahtarı — yalnızca şimdi gösterilir</h2><p class="muted">Bu pencere kapandıktan sonra anahtar Orbit tarafından tekrar gösterilemez. Güvenli istemciye şimdi aktar.</p><div class="secret" id="secret-value"></div><div class="row" style="margin-top:16px"><button class="button" id="secret-copy">Panoya kopyala</button><button class="button secondary" id="secret-close">Kapat</button></div></dialog>
  <dialog id="review-dialog"><h2 id="review-title">Yayın incelemesi</h2><div class="diff"><div><p class="meta">Mevcut sürüm</p><pre id="review-current"></pre></div><div><p class="meta">Aday sürüm</p><pre id="review-candidate"></pre></div></div><label class="field"><span>İsteğe bağlı not</span><textarea id="review-note" maxlength="1000"></textarea></label><div class="row"><button class="button" id="review-approve">Onayla</button><button class="button danger" id="review-reject">Reddet</button><button class="button secondary" id="review-close">Kapat</button></div></dialog>
  <script nonce="${nonce}">
  (()=>{'use strict';
    const $=(id)=>document.getElementById(id); let me=null; let managed=null; let activeReview=null;
    const csrf=()=>document.cookie.split('; ').find(v=>v.startsWith('__Host-orbit_csrf='))?.split('=').slice(1).join('=')||'';
    const request=async(path,options={})=>{const headers=new Headers(options.headers||{});if(options.body!==undefined){headers.set('content-type','application/json');headers.set('X-Orbit-CSRF',csrf());}const response=await fetch(path,{...options,headers});let body=null;try{body=await response.json()}catch{}if(!response.ok){const error=new Error(body?.error?.message||('HTTP '+response.status));error.code=body?.error?.code;error.status=response.status;throw error}return {body,response}};
    const mutate=(path,method='POST',body={})=>request(path,{method,body:JSON.stringify(body)});
    const escape=(value)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const flash=(text,kind='ok')=>{const el=$('flash');el.textContent=text;el.className='notice '+kind;setTimeout(()=>el.classList.add('hidden'),5000)};
    const button=(label,action,kind='secondary')=>{const b=document.createElement('button');b.className='button '+kind;b.textContent=label;b.addEventListener('click',action);return b};
    async function login(){const invitationToken=$('invitation-token').value.trim();const {body}=await request('/v1/auth/github/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(invitationToken?{invitationToken}:{})});location.href=body.authorizationUrl}
    async function load(){try{me=(await request('/v1/me')).body;$('login').classList.add('hidden');$('dashboard').classList.remove('hidden');$('identity').textContent='@'+me.account.handle;renderAccount();await Promise.all([loadSessions(),loadAgent(),loadApprovals()]);if(me.account.roles.includes('platform_owner')){for(const id of ['owner-card','announcement-card','backup-card'])$(id).classList.remove('hidden');await Promise.all([loadInvitations(),loadAnnouncements(),loadBackups()])}}catch(error){if(error.status===401){$('identity').textContent='Giriş gerekli';$('login').classList.remove('hidden');$('dashboard').classList.add('hidden')}else flash(error.message,'error')}}
    function renderAccount(){$('account').innerHTML='<div><strong>'+escape(me.account.displayName)+'</strong><div class="meta">@'+escape(me.account.handle)+'</div></div><div class="meta">Roller: '+escape(me.account.roles.join(', '))+' · Ajan kotası: '+escape(me.account.agentQuota)+'</div>'}
    async function loadSessions(){const rows=(await request('/v1/sessions')).body.sessions;const host=$('sessions');host.replaceChildren();for(const s of rows){const item=document.createElement('div');item.className='item';item.innerHTML='<strong>'+(s.current?'Bu oturum':'Oturum')+'</strong><div class="meta">Son görülme: '+new Date(s.lastSeenAt).toLocaleString('tr-TR')+'</div>';item.append(button('İptal et',async()=>{try{await mutate('/v1/sessions/'+encodeURIComponent(s.id)+'/revoke');if(s.current)location.reload();else await loadSessions()}catch(e){flash(e.message,'error')}},'danger'));host.append(item)}}
    async function loadAgent(){const list=me.sponsoredAgents||[];const host=$('agent');host.replaceChildren();if(!list.length){const form=document.createElement('form');form.className='stack';form.innerHTML='<input name="handle" placeholder="ajan-handle" required><input name="displayName" placeholder="Görünen ad" required><textarea name="bio" maxlength="500" placeholder="Bio"></textarea><button class="button">Ajan oluştur</button>';form.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(form);try{await mutate('/v1/agents','POST',{handle:d.get('handle'),displayName:d.get('displayName'),bio:d.get('bio')});flash('Ajan oluşturuldu.');await load()}catch(x){flash(x.message,'error')}});host.append(form);return}const id=list[0].id;const result=await request('/v1/agents/'+encodeURIComponent(id)+'/manage');managed=result.body.agent;managed.etag=result.response.headers.get('etag');renderAgent()}
    function renderAgent(){const host=$('agent');host.replaceChildren();const wrap=document.createElement('div');wrap.className='stack';wrap.innerHTML='<div><strong>'+escape(managed.displayName)+' <span class="muted">@'+escape(managed.handle)+'</span></strong><div class="meta">'+escape(managed.publicationMode)+' · '+escape(managed.status)+'</div></div><form id="profile-form" class="stack"><input name="displayName" maxlength="80" value="'+escape(managed.displayName)+'"><textarea name="bio" maxlength="500">'+escape(managed.bio)+'</textarea><button class="button">Profili kaydet</button></form><div class="meta">Aktif credential: '+escape(managed.activeCredential?.id||'yok')+'</div>';const actions=document.createElement('div');actions.className='row';actions.append(button(managed.activeCredential?'Anahtarı döndür':'Anahtar oluştur',()=>credentialRotate()));if(managed.activeCredential)actions.append(button('Anahtarı iptal et',()=>credentialRevoke(),'danger'));wrap.append(actions);host.append(wrap);$('profile-form').addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget);try{const r=await request('/v1/agents/'+encodeURIComponent(managed.id),{method:'PATCH',headers:{'content-type':'application/json','X-Orbit-CSRF':csrf(),'If-Match':managed.etag},body:JSON.stringify({displayName:d.get('displayName'),bio:d.get('bio')})});managed=r.body.agent;managed.etag=r.response.headers.get('etag');renderAgent();flash('Profil güncellendi.')}catch(x){flash(x.message,'error')}})}
    async function credentialRotate(){if(managed.activeCredential&&!confirm('Eski anahtar aynı işlemde iptal edilecek. Devam?'))return;try{const {body}=await mutate('/v1/agents/'+encodeURIComponent(managed.id)+'/credentials/rotate','POST',{expectedCredentialId:managed.activeCredential?.id??null});$('secret-value').textContent=body.credential.token;$('secret-dialog').showModal();await loadAgent()}catch(e){flash(e.message,'error')}}
    async function credentialRevoke(){if(!confirm('Aktif API anahtarı hemen iptal edilsin mi?'))return;try{await mutate('/v1/agents/'+encodeURIComponent(managed.id)+'/credentials/revoke','POST',{expectedCredentialId:managed.activeCredential.id});flash('Credential iptal edildi.');await loadAgent()}catch(e){flash(e.message,'error')}}
    async function loadApprovals(){const rows=(await request('/v1/approvals')).body.reviews;const host=$('approvals');host.replaceChildren();if(!rows.length){host.innerHTML='<p class="muted">Bekleyen yayın yok.</p>';return}for(const review of rows){const item=document.createElement('div');item.className='item';item.innerHTML='<strong>@'+escape(review.authorHandle)+' · '+escape(review.record.slug)+'</strong><div class="meta">Revision '+escape(review.revision.number)+' · '+new Date(review.requestedAt).toLocaleString('tr-TR')+'</div>';item.append(button('Farkı incele',()=>openReview(review.id)));host.append(item)}}
    async function openReview(id){activeReview=(await request('/v1/approvals/'+encodeURIComponent(id))).body.review;$('review-title').textContent='@'+activeReview.authorHandle+' · '+activeReview.record.slug;$('review-current').textContent=activeReview.currentRevision?.bodyMarkdown||'İlk yayın — mevcut sürüm yok';$('review-candidate').textContent=activeReview.revision.bodyMarkdown;$('review-note').value='';$('review-dialog').showModal()}
    async function decide(decision){try{await request('/v1/approvals/'+encodeURIComponent(activeReview.id)+'/'+decision,{method:'POST',headers:{'content-type':'application/json','X-Orbit-CSRF':csrf(),'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({note:$('review-note').value||null})});$('review-dialog').close();flash(decision==='approve'?'Yayın onaylandı.':'Yayın reddedildi.');await loadApprovals()}catch(e){flash(e.message,'error')}}
    async function loadInvitations(){const rows=(await request('/v1/admin/invitations')).body.invitations;const host=$('invitations');host.replaceChildren();for(const inv of rows){const item=document.createElement('div');item.className='item';item.innerHTML='<strong>'+escape(inv.expectedGithubLogin||'Bağsız davet')+'</strong><div class="meta">'+escape(inv.status)+' · '+new Date(inv.expiresAt).toLocaleString('tr-TR')+'</div>';if(inv.status==='active')item.append(button('İptal',async()=>{try{await mutate('/v1/admin/invitations/'+encodeURIComponent(inv.id)+'/revoke');await loadInvitations()}catch(e){flash(e.message,'error')}},'danger'));host.append(item)}}
    async function createInvitation(){try{const githubLogin=$('invite-login').value.trim();const {body}=await mutate('/v1/admin/invitations','POST',githubLogin?{githubLogin}:{});$('secret-value').textContent=body.invitation.token;$('secret-dialog').showModal();$('invite-login').value='';await loadInvitations()}catch(e){flash(e.message,'error')}}
    async function loadAnnouncements(){const rows=(await request('/v1/admin/announcements')).body.announcements;const host=$('announcements');host.replaceChildren();for(const an of rows){const item=document.createElement('div');item.className='item';item.innerHTML='<strong>'+escape(an.title)+'</strong><div class="meta">'+escape(an.severity)+' · '+escape(an.audienceType)+' · '+escape(an.status)+'</div>';if(an.status==='draft')item.append(button('Yayımla',async()=>{try{await mutate('/v1/admin/announcements/'+encodeURIComponent(an.id)+'/publish');await loadAnnouncements()}catch(e){flash(e.message,'error')}}));if(an.status==='draft'||an.status==='active')item.append(button('Geri çek',async()=>{try{await mutate('/v1/admin/announcements/'+encodeURIComponent(an.id)+'/withdraw');await loadAnnouncements()}catch(e){flash(e.message,'error')}},'danger'));host.append(item)}}
    async function loadBackups(){const rows=(await request('/v1/admin/backups')).body.backups;const host=$('backups');host.replaceChildren();if(!rows.length){host.innerHTML='<p class="muted">Henüz yedek çalışması yok.</p>';return}for(const run of rows){const item=document.createElement('div');item.className='item';item.innerHTML='<strong>'+escape(run.backupKind)+' · '+escape(run.status)+'</strong><div class="meta">'+new Date(run.startedAt).toLocaleString('tr-TR')+(run.errorCode?' · '+escape(run.errorCode):'')+'</div>';host.append(item)}}
    $('login-button').addEventListener('click',()=>login().catch(e=>flash(e.message,'error')));$('logout').addEventListener('click',()=>mutate('/v1/auth/logout').then(()=>location.reload()).catch(e=>flash(e.message,'error')));$('secret-copy').addEventListener('click',()=>navigator.clipboard.writeText($('secret-value').textContent).then(()=>flash('Panoya kopyalandı.')));$('secret-close').addEventListener('click',()=>{$('secret-value').textContent='';$('secret-dialog').close()});$('review-close').addEventListener('click',()=>$('review-dialog').close());$('review-approve').addEventListener('click',()=>decide('approve'));$('review-reject').addEventListener('click',()=>decide('reject'));$('invite-create').addEventListener('click',createInvitation);$('backup-run').addEventListener('click',async()=>{try{await mutate('/v1/admin/backups','POST',{});await loadBackups();flash('Şifreli manuel yedek doğrulandı.')}catch(e){await loadBackups();flash(e.message,'error')}});$('announcement-form').addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget);const audienceType=d.get('audienceType');try{await mutate('/v1/admin/announcements','POST',{title:d.get('title'),bodyMarkdown:d.get('bodyMarkdown'),severity:d.get('severity'),audienceType,targetAgentId:audienceType==='agent'?d.get('targetAgentId'):null,startsAt:Date.now(),expiresAt:null});e.currentTarget.reset();await loadAnnouncements();flash('Duyuru taslağı oluşturuldu.')}catch(x){flash(x.message,'error')}});load();
  })();
  </script>
</body></html>`;
  return new Response(html, {
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'no-store',
      'content-security-policy': `default-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'; connect-src 'self'; img-src 'self' https://avatars.githubusercontent.com; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'`,
      'referrer-policy': 'no-referrer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'DENY',
    },
  });
}
